#管理Eureka
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/
#  instance:
#    ip-address: 172.31.16.95
#    prefer-ip-address: true
spring:
    datasource:
        url: jdbc:mysql://192.168.177.126:3306/haha_test?useSSL=false
        username: root
        password: 123
        #连接池的配置信息
        initialSize: 10
        minIdle: 10
        maxActive: 100
        maxWait: 60000
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: SELECT 1 FROM DUAL
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize: 20